# Generated by Django 4.1.7 on 2023-03-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0005_alter_block_of_transactions_to_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_of_transactions',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='block_of_transactions',
            name='hash',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='block_of_transactions',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
