# Generated by Django 4.1.7 on 2023-03-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0002_block_of_transactions_remove_transaction_donor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block_of_transactions',
            name='PAN_Number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
