# Generated by Django 4.1.7 on 2023-03-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0004_block_of_transactions_adhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_of_transactions',
            name='to_account',
            field=models.CharField(blank=True, default='1234567891112131', max_length=100, null=True),
        ),
    ]
