# Generated by Django 4.1.7 on 2023-03-29 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0007_rename_donor_block_of_transactions_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block_of_transactions',
            old_name='user',
            new_name='user_id',
        ),
    ]
