# Generated by Django 4.1.7 on 2023-04-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0009_block_of_transactions_donation_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
