# Generated by Django 4.1.7 on 2023-04-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CharityApp', '0011_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block_of_transactions',
            name='hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='block_of_transactions',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
